### ISSUE TITLE
CCtalk support for curve devices

### ISSUE THREAD

**Issue by Kuro07** [PyramidTechnologies/Feedback#1]
Is there any chance of cctalk being supported for this api? The ability to change which bills to reject and accept would be great.

**Comment by ghost** [comment]
A ccTalk API is not on our road map but this feature that you're seeking is available and fully functional in our RS-232 API. Contact support@pyramidacceptors.com to get a copy of the RS-232 firmware for whichever current Pyramid Acceptor and country you are targeting.
